### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by unionTime** [TensorWorks/LandscapeGen#1]
I have successfully installed the plugin, but I don’t know how to use the plug-in to import GIS data.
Is there a tutorial?

**Comment by MadaraPremawardhana** [comment]
I managed to successfully install the plugin and imported GIS data from USGS (as GeoTIFF). But since there is an RGB field needed I still couldn't create landscape successfully. Any tutorials or suggestions on where to get data from? 
When I tried to convert 8-bit Heightmap to RGB using a color ramp using QGIS there occurs a data loss, Therefore I still couldn't get a RGB dataset created.

**Comment by MadaraPremawardhana** [comment]
> I have successfully installed the plugin, but I don’t know how to use the plug-in to import GIS data.
> Is there a tutorial?

I managed to create a landscape using this plugin using a .TIF (A GeoTIFF file) which contained RGB channels. I downloaded the file from USGS data. `https://earthexplorer.usgs.gov/`

You'll need to use the satellite image from the retrieved datasets.

**Comment by adamrehn** [comment]
No, there is no tutorial currently available for using this plugin. You can use the Editor Utility Widgets from the [Examples](https://github.com/TensorWorks/LandscapeGen/tree/main/Content/Examples) folder to import data from either GDAL or Mapbox, by right-clicking on the widget asset in the Unreal Editor and selecting "Run", which will open a panel with inputs to configure the data source.

It's unlikely that we will end up creating any educational resources for using this plugin, since I'm unsure as to whether the plugin will even continue to be relevant with the [heavy investment in this space from players such as Cesium](https://cesium.com/platform/cesium-for-unreal/).
